fix: org status sometimes cannot be changed to Deployed
bestchains/fabric-operator pull request #94
Opened 2023-02-08 08:47 UTC by Abirdcfly

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

Fix #79 

need #73 merged first.

2023-02-08 09:23 UTC, Abirdcfly commented
todo: stacklog

2023-02-08 09:28 UTC, Abirdcfly commented on pkg/offering/base/organization/organization.go
> +		ca := &current.IBPCA{}
todo name

2023-02-08 09:38 UTC, Abirdcfly commented on controllers/organization/update.go
> +	caUpdated    bool
caStatusUpdated

2023-02-09 01:34 UTC, bjwswang requested changes

2023-02-09 01:50 UTC, 0xff-dev approved these changes

2023-02-10 02:33 UTC, bjwswang approved these changes
/LGTM

2023-02-10 03:06 UTC, merged