fix: correct network status
bestchains/fabric-operator pull request #96
Opened 2023-02-08 09:38 UTC by Abirdcfly

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

Fix #83

need #73 merged first.

2023-02-09 01:23 UTC, 0xff-dev approved these changes

2023-02-09 01:34 UTC, bjwswang requested changes

2023-02-09 01:42 UTC, Abirdcfly commented on pkg/offering/base/network/network.go
> +			return common.Result{Status: &orderer.Status.CRStatus}, nil
> will `network.status.channels` will overrided ?

Nop, the overall logic has not changed.

The only difference is that the previous network state was only `Created`, but now `Deployed` has been added according to the state of the orderer.

2023-02-09 02:16 UTC, Abirdcfly commented on controllers/network/network_controller.go
> +	err = c.Watch(&source.Kind{Type: &current.IBPOrderer{}}, &handler.EnqueueRequestForOwner{
Just monitor those orderers has OwnerReferences to network. These orderers are root orderer.

2023-02-10 02:54 UTC, bjwswang approved these changes
/LGTM

2023-02-10 03:06 UTC, merged